name: notepad_flutter
description: A notepad app, made with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  floor: ^1.4.1
  path: ^1.8.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  sqflite: ^2.2.4+1
  floor_generator: ^1.4.1
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
